version: "3.8"

networks:
  backend:
  typescript:
  frontend:
volumes:
  db_data:
    driver: local
services:
  nginx:
    image: nginx:latest
    ports:
      - 8000:80 
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./backend:/var/www/html 
    depends_on:
      - app
      - mysql
    networks:
      - backend

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/src:/app/src
      # - ./frontend:/usr/src/app
      # - /usr/src/app/node_modules
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - frontend

  typescript:
    container_name: typescript
    build:
      context: ./event-typescript
      dockerfile: Dockerfile
    volumes:
      - ./event-typescript/src:/app/src
      # - /usr/src/app/node_modules
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - typescript

  php-fpm:
    build:
      context: ./backend
      target: dev
    volumes:
      # - ./app/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./backend:/var/www/html # To change project folder name
    ports:
      - '9000:9000'
    depends_on:
      - mysql
    networks:
      - backend

  mysql:
    image: mysql:8.0
    ports:
      - 3309:3306 # To change mysql port number
    environment:
      MYSQL_ROOT_PASSWORD: rootPass
      MYSQL_USER: root # To change database user
      MYSQL_PASSWORD: password # To change database user password
      MYSQL_DATABASE: eventdb # To change database name
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dev_pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3309
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8183:80
    networks:
      - backend

